sudo: required
language: python

env:
  global:
    - DOCKER_IMAGE=getpagespeed/rpmbuilder
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=7
    - OS_TYPE=centos OS_DIST=epel OS_VERSION=6
    - OS_TYPE=fedora OS_DIST=epel OS_VERSION=27
services:
  - docker

install: true

script:
  - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}  
  - stat *.rpm
  # we want to test complete build, so we build final RPM (no -e "SRPM_ONLY=1" switch) + fix build script inside the image (for older bash in EL6)
  # - docker run -v ${PWD}:/sources -v ${PWD}:/output:Z ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION} /bin/bash -c "rm -rf /etc/yum.repos.d/CentOS-Vault.repo; rm -rf /etc/yum.repos.d/CentOS-Sources.repo; sed -i 's/-v OUTPUT_UID/-z "${OUTPUT_UID}"/' /usr/bin/build; /usr/bin/build"
  
